"""add government fund fields

Revision ID: 3ffcfd6cfb56
Revises: 76c8a7b059cf
Create Date: 2025-12-29 04:15:14.834804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffcfd6cfb56'
down_revision = '76c8a7b059cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expenses_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('net_benefits', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_fund', schema=None) as batch_op:
        batch_op.drop_column('net_benefits')
        batch_op.drop_column('expenses_description')

    # ### end Alembic commands ###
